version: 0.2

phases:
  install:
    commands:
      - npm i npm@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Pre_build Phase
      - npm install
  build:
    commands:
      - echo Build Phase
      - npm run build
  post_build:
    commands:
      - echo PostBuild Phase
      - - |
        if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then
          aws s3 sync ./dist s3://static-bucket-vue-deploy-with-codepipeline-build
        fi       